'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Slab_Opc

    '''<summary>
    '''Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message As Global.Arad.Message

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''OpcSubmit_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpcSubmit_check As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SlabId_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabId_Txt As Global.Arad.CheckSlabCode

    '''<summary>
    '''Continue_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Continue_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OpcSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpcSubmit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''OPCRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCRow As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OperationTitle_DD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OperationTitle_DD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OpcDesc_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpcDesc_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tools_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tools_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Fixcher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fixcher As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Fixcher_Validation_Lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fixcher_Validation_Lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TarefehWorker_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TarefehWorker_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NumWorker_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumWorker_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TanzimTime_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TanzimTime_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SlabTime_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabTime_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''addToList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addToList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OPCList_GV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCList_GV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''OPCSubmit_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCSubmit_Btn As Global.System.Web.UI.WebControls.Button
End Class
