'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Slab_Insert_Assembly

    '''<summary>
    '''ScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message As Global.Arad.Message

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''AssemblySubmit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblySubmit1 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SlabIdCheck_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabIdCheck_Txt As Global.Arad.SlabId_Check

    '''<summary>
    '''SlabName_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabName_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PerSlabName_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerSlabName_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SlabFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabFile As Global.Arad.File_Upload

    '''<summary>
    '''SlabDesc_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabDesc_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submit_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AssemblySubmit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblySubmit2 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SlabId2_Lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabId2_Lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SlabName2_Lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabName2_Lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PerSlabName2_Lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerSlabName2_Lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SlabFile2_LBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabFile2_LBtn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rowNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowNumber As Global.Arad.IntValidation

    '''<summary>
    '''UP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Check_SlabId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_SlabId As Global.Arad.CheckSlabCode

    '''<summary>
    '''tedad_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tedad_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFV1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''addToList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addToList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''slabsList_GV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slabsList_GV As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Eslah_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eslah_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AssemblySubmit_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblySubmit_Btn As Global.System.Web.UI.WebControls.Button
End Class
