'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Slab_Insert_Sefareshi

    '''<summary>
    '''Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message As Global.Arad.Message

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''SefareshiSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SefareshiSubmit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SlabId_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabId_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SlabName_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabName_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PerSlabName_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerSlabName_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SlabFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabFile As Global.Arad.File_Upload

    '''<summary>
    '''SlabDesc_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabDesc_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submit_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ViewEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewEdit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SlabIdEdit_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabIdEdit_Txt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SlabNameEdit_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabNameEdit_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PerSlabNameEdit_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerSlabNameEdit_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SlabDescEdit_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabDescEdit_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Edit_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Btn As Global.System.Web.UI.WebControls.Button
End Class
