'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Slab_Insert_Tolidi

    '''<summary>
    '''Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message As Global.Arad.Message

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''TolidiSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TolidiSubmit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''SlabIdCheck_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabIdCheck_Txt As Global.Arad.SlabId_Check

    '''<summary>
    '''SlabName_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabName_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PerSlabName_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerSlabName_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AvvaliyehSearch_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvvaliyehSearch_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Avvaliye_DD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Avvaliye_DD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Megdar_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Megdar_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''VazneMasrafi_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VazneMasrafi_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''VazneKhales_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VazneKhales_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TedadeHasele_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TedadeHasele_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TabageyeBorade_DD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabageyeBorade_DD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SlabFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabFile As Global.Arad.File_Upload

    '''<summary>
    '''SlabDesc_Txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlabDesc_Txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submit_Btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Btn As Global.System.Web.UI.WebControls.Button
End Class
